add cloud init ability for ubunut. Fix issues when setting hostname/u…
ERIGrid2/riasc-provisioning pull request #2
Opened 2021-11-27 22:04 UTC by cl0-de

Add handling for ubuntu clount-init

2024-04-24 06:34 UTC, stv0g commented
I guess this needs some rebasing / squashing?

2024-04-24 09:30 UTC, windrad6 commented
Yes we just merged into master in our fork and will have to cleanup in the next step

2024-05-28 07:07 UTC, stv0g approved these changes, later dismissed

2024-05-28 07:09 UTC, stv0g commented
@windrad6 Do you want to have these changes reviewed?

2024-11-29 18:39 UTC, stv0g requested changes

2024-11-29 18:39 UTC, stv0g commented on rpi/create_image.sh
> +		VAULT_KEY=$(tr -dc A-Za-z0-9 </dev/urandom | head -c 20; echo)
```suggestion
		VAULT_KEY=$(tr -dc A-Za-z0-9 < /dev/urandom | head -c 20; echo)
```

2024-11-29 18:39 UTC, stv0g commented on rpi/create_image.sh
> +if [! -z "$VAULT_KEY" ]; then
```suggestion
if [ ! -z "$VAULT_KEY" ]; then
```

2025-03-05 11:32 UTC, stv0g commented
The ERIGrid project is ending. I dont see that this PR will be used within the context of the project.

Therefore its probably better to fork this repo to your own space.

2025-03-05 11:32 UTC, closed without merging